<h1 align="center">Física Computacional.</h1>
<h1 align="center">Semestre 2027-1</h1>

<h2>Sergio A. Alcalá Corona </h2> 

---
### Rodrigo Vega Vilchis
### Joel Gómez Uribe
---

<h1 align="center">Programación para la física computacional</h1> 

## 1.2. Listas, vectores y matrices (arreglos numpy)
---

En Python hay 3 tipos diferentes de arreglos. Las **listas**, las **n-adas** (o tuples) y los **arreglos numpy**, estos últimos son mas robustos y con ellos se puede representar vectores e incluso matrices.

## Listas

La estructura de datos principal en Python es la lista. Consiste literalmente en una lista ordenada de cosas, y
reemplaza a los arreglos en otros lenguajes. La diferencia es que las listas en *Python* son automáticamente de longitud variable, y pueden contener objetos de cualquier tipo.

Una lista se define entre corchetes (`[y]`):

In [1]:
l = [3, 4, 6]

In [5]:
l[0]

3

In [6]:
len(l)

3

In [14]:
r = [ 1, 1, 2, 3, 5, 8, 13, 21 ]
print(r)

[1, 1, 2, 3, 5, 8, 13, 21]


In [12]:
r[5]+22

30

In [13]:
len(r)

8

Puede contener cualquier cosa, ¡incluyendo a otras listas!:



In [15]:
l2 = [3.5, -1, "hola", [1.0, [3, 17]]]
l2[3][1][0]

3

In [17]:
l2(2)[1]

TypeError: 'list' object is not callable

Los elementos de la lista se pueden extraer y cambiar usando la notación `lista[i]`, donde `i` indica el número del elemento, empezando desde `0`:



In [18]:
l3 = [1, 2, 3]
print(l3[0],l3[1])

1 2


Y así también se pueden reasignar sus valores: 

In [19]:
l[0] = 5
l

[5, 4, 6]

In [ ]:
r = [ 1.0,1.5, -2.2 ]
r[1] = 3.5

print(r)

Se puede hacer una lista a partir de diferentes variables:

In [20]:
x = 99
y = 1.5
z = -2.2
r = [ x, y, z ]

print(r)

[99, 1.5, -2.2]


In [21]:
r

[99, 1.5, -2.2]

O bien, definir una lista a partir de operaciones con variables:

In [22]:
import math as mt

r = [ 2*x, x+y, z/mt.sqrt(x**2+y**2) ]
print(r)

[198, 100.5, -0.022219671901192166]


In [23]:
r = [ 1.0, 1.5, -2.2 ]
norma = mt.sqrt(r[0]**2 + r[1]**2 + r[2]**2)
print(norma)

2.8442925306655784


Se pueden sumar los elementos de la lista de la siguiente manera:

In [24]:
r = [ 1, 1.5, -2.2 ]
total = sum(r)
print(total)

0.2999999999999998


In [25]:
sum(r)

0.2999999999999998

In [27]:
r**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [29]:
round(total,6)

0.3

In [34]:
a=1/3
b=5.929233

In [37]:
round(a,4)

0.3333

In [33]:
total

0.2999999999999998

o calcular el promedio de las mismas

In [30]:
r = [ 1.0, 1.5, -2.2 ]
promedio = sum(r)/len(r)
print(promedio)

0.09999999999999994


#### La función `map`


Una función especialmente útil para las listas es `map`, que permite aplicar funciones ordinarias, como `log`  o `sqrt`, a todos los elementos de una lista a la vez. Así, `map(log,r)` toma el logaritmo natural de cada elemento de la lista `r`:

In [38]:
r = [ 1.0, 1.5, 2.2, mt.e ]
logr = list(map(mt.log,r))

print(logr)

[0.0, 0.4054651081081644, 0.7884573603642703, 1.0]


In [40]:
print(r)

[1.0, 1.5, 2.2, 2.718281828459045]


mt.pow(2,3)

In [39]:
for i in (map(mt.log,r)):
    print(i)

0.0
0.4054651081081644
0.7884573603642703
1.0


In [41]:
mt.pow(2,3)

8.0

In [47]:
L =  list(map(round,r))
L = list(map(mt.factorial,L))
L

[1, 2, 2, 6]

### Rebanadas (“*slices*”) 

También se pueden manipular rebanadas (“*slices*”) de la lista con la notación `l[i:j]` donde `i` indica el elemento a partir del cual se va a tomar la rebanada y `j` indica hasta que elemento se va a tomar la rebanada **sin incluirlo**.

In [48]:
ls = [1, 2, 3, 6, 7]

In [49]:
ls[1:4]

[2, 3, 6]

In [ ]:
ls[2:]

In [50]:
ls[1:6]

[2, 3, 6, 7]

In [ ]:
r = [ 1, 3, 5, 7, 9, 11, 13, 15 ]
s = r[2:5+1]

print(s)

In [ ]:
len(r)

In [ ]:
r[0:len(r)]

In [ ]:
r[2:]

In [ ]:
r [:5]

¿qué pasa si no ponemos nada?

In [ ]:
r [:]

#### Función `len()`

La longitud de una lista se puede encontrar con `len(`*`lista`*`)`:

In [ ]:
len(ls)

#### Funciones `append()` y `pop()`



Se pueden agregar elementos a la lista con `append()`:

In [ ]:
l = [] # asi creamos una lista vacía
l

In [53]:
l.append(17)
l.append(3)


In [52]:
l

[5, 4, 6]

In [ ]:
# l.pop(17)

In [ ]:
l

In [ ]:
print (l, len(l))

In [ ]:
r = [ 1.0, 1.5, -2.2 ]
print(r)

In [ ]:
r.append(6.1)
r

In [ ]:
r = [ 1.0, 1.5, -2.2]

x = 0.8
r.append(2*x+1)

print(r)

In [ ]:
r = []  # lista vacía

r.append(1.0)
r.append(1.5)
r.append(-2.2)
print(r)


y de igual manera se pueden remover elementos de la lista con `pop()`:

In [ ]:
r = [ 1.0, 1.5, -2.2, 2.6 ]

r.pop()
print(r)

**Nota**: `append()` y `pop()` manejan la lista como una `pila` (_stack_), esto es: "lo primero que entra es lo ultimo que sale y viceversa.

Como siempre, las otras operaciones que se pueden llevar a cabo con la lista se pueden averiguar en ipython con:
`l.<TABULADOR>`

## *COPIA* de un objeto

r2=r

In [ ]:
r2

In [ ]:
r2 = r.copy()

In [ ]:
r.pop()

In [ ]:
r

In [ ]:
r2 = 555

In [ ]:
r2

## Arreglos numpy (vectores).

Por lo general las listas y *tuples* se utilizan para guardar y manipular datos. Sin embargo, las listas no se comportan como vectores, y menos como matrices (al sumarlos no se comportan de la manera adecuada, etc.). El propósito de la biblioteca numpy es justamente el de proporcionar objetos que representan a vectores y matrices matemáticos, con todas las bondades que traen consigo este tipo de objetos.

La biblioteca se carga con:

In [3]:
import numpy as np

In [8]:
l1=np.linspace(1,100,1000)

Y provee muchas funciones para trabajar con vectores y matrices.


Los vectores se llaman (aunque es un poco confuso) **arrays**, (arreglos) y se pueden crear de distintas maneras. Son como listas, pero con propiedades y **métodos** adicionales para funcionar como objetos matemáticos. La manera más general de crear un vector es justamente convirtiendolo desde una lista de números:

In [56]:
a = np.array( [1, 2, -1, 100] )

In [61]:
a**2

array([  4,  16,  36,  64, 100, 144, 196, 256])

In [57]:
a = np.array([1.0,1.5,-2.2] ,float)

In [62]:
type(a)

numpy.ndarray

In [63]:
r = np.array(r)

In [65]:
r+a

array([ 2. ,  3. , -4.4])

In [67]:
print(np.dot(a,a))

8.09


In [64]:
r = [ 1.0, 1.5, -2.2 ]
a = np.array(r,float)

Aqui también se pueden hacer rebandas (*"slices"*)

In [59]:
a = np.array([2,4,6,8,10,12,14,16] ,int)

b = a[3 :6]
print(b)

[ 8 10 12]


In [60]:
print(a[3:])
print(a[:6])


[ 8 10 12 14 16]
[ 2  4  6  8 10 12]


In [ ]:
a [:]

Un vector de este tipo puede contener sólo un tipo de objetos, a diferencia de una lista normal de *Python*. Si todos los números en la lista son enteros, entonces el tipo del arreglo también lo es, como se puede comprobar con

In [68]:
a.dtype

dtype('float64')

Es común querer crear vectores de cierto tamaño con todas las entradas en ceros. Esto se puede hacer con la biblioteca `zeros` de `numpy`:

In [69]:
b = np.zeros(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [70]:
a = np.zeros(4,int)
print(a)

[0 0 0 0]


In [ ]:
a = np.zeros(50, complex)
print(a)

o bien, todos unos:

In [ ]:
b = np.ones(10)
print(b)

Si se quiere crear un **arreglo "vacio"**, directamente (es decir, sin crear primero la lista vacia), se puede hacer con la biblioteca `empty` de `numpy`:

In [ ]:
a = np.empty(4,float)

In [ ]:
a

In [1]:
dominio = np.arange(-3,3,1) 
dominio

NameError: name 'np' is not defined

In [2]:
contradominio = np. sin(dominio)

NameError: name 'np' is not defined

También hay distintas maneras de crear vectores que consisten en rangos ordenados, por ejemplo **`arange`**, que funciona como `range`, con un punto inicial, un punto final, y un paso:

In [83]:
np.sin(dominio)

array([-0.14112001, -0.90929743, -0.84147098,  0.        ,  0.84147098,
        0.90929743])

In [84]:
a = np.arange(0., 10., 0.1)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

y **`linspace`**, donde se especifica puntos iniciales y finales y un número de entradas:

In [85]:
l = np.linspace(0., 10., 11)
l

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Una notación abreviada para construir vectores es `r_`, que se puede pensar como una abreviación de *“vector renglón”*:


In [ ]:
a = np.r_[1,2,10,-1.]
a

Este método se extiende para dar una manera rápida de construir rangos:

In [ ]:
np.r_[3:7]

In [ ]:
np.r_[3:7:0.5]

### Aritmetica con arreglos

Los vectores creados de esta manera se pueden sumar, restar etc., como si fueran vectores matemáticos. Todas las operaciones se llevan a cabo entrada por entrada:

In [4]:
v1 = np.array( [1., 4., 7. ])
v2 = np.array( [1., 2., -2. ])

print(v1, v2)

[1. 4. 7.] [ 1.  2. -2.]


In [5]:
v1+v2

array([2., 6., 5.])

In [6]:
v1-v2

array([0., 2., 9.])

In [7]:
v1*v2

array([  1.,   8., -14.])

In [8]:
v1/v2

array([ 1. ,  2. , -3.5])

In [9]:
v1**v2

array([ 1.        , 16.        ,  0.02040816])

In [10]:
a = np.array([1.0,1.5,-2.2,3.5] ,float)

In [11]:
a[0] = a[1] + 1
a

array([ 2.5,  1.5, -2.2,  3.5])

In [13]:
a = np.array([1,2,3,4] ,int)
b = 2*a
print(b)

[2 4 6 8]


In [ ]:
a = np.array([1,2,3,4] ,int)
print(a+1)

Las funciones más comunes entre vectores ya están definidas en **numpy**, entre las cuales se encuentran `dot(v1,v2)` para productos escalares de dos vectores de la misma longitud, y `cross(v1,v2)` para el producto cruz de dos vectores de longitud 3.

In [16]:
a = np.array([1,2,3] ,int)
b = np.array([2,4,6] ,int)

print(np.cross(a,b))

[0 0 0]


In [ ]:
print(v1)
print(v2)

In [ ]:
np.dot(v1,v2)

In [ ]:
np.cross(v1,v2)

Además, cualquier función matemática como **`sin`** y **`exp`** se puede aplicar directamente a un vector, `y` regresará un vector compuesto por esta función aplicada a cada entrada del vector. Es más: al definir una función el usuario, esta función normalmente también se pueden aplicar directamente a un vector:


In [ ]:
def gauss(x):
    return 1./(np.sqrt(2.)) * np.exp(-x*x / 2.)

In [18]:
import math as mt 

In [20]:
mt.cos(mt.pi)

-1.0

In [27]:
wl = np.array([mt.pi, mt.pi/2, 2*mt.pi])
mt.cos(np.pi)
np.cos(wl)

array([-1.000000e+00,  6.123234e-17,  1.000000e+00])

In [29]:
def gauss(x):
    return 1./(np.sqrt(2.))* np.exp(-x*x / 2)

In [40]:
g = gauss( np.r_[0:10] )
g[len(g)-1]

np.float64(1.8220424253541317e-18)

Para acceder a subpartes de un vector, la misma sintaxis funciona como para listas: se extraen componentes (entradas) individuales con

In [42]:
wl len(wl) - 1

SyntaxError: invalid syntax (3839045801.py, line 1)

In [38]:
np.r_[0:100]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
a = np.array([0, 1, 2, 3])
print(a[0], a[2])

y subvectores con

In [ ]:
b = a[1:3]
b

Nótese, sin embargo, que en este caso la variable `b` no es una copia de esta parte de `a`. Más bien, es una vista de `a`, así que ahora si hacemos:

In [ ]:
b[1] = 10
print(b)
print(a)

entonces la entrada correspondiente de a ¡también cambia! Este fenómeno también funciona con listas:

In [ ]:
l=[1,2,3]; k=l; k[1] = 10

In [ ]:
l

In [ ]:
k

En general, en *Python* las variables son nombres de objetos; al poner `b = a`, **tenemos ¡un mismo objeto con dos nombres!**

Por lo que si realmente queremos una copia de un arreglo, podemos usar la función `copy()` de `numpy`

In [ ]:
b = np.copy(a)
b

In [ ]:
b[1] = 10
print(b)
print(a)

### *Ejercicio 1:* 
Suponga que los arreglos a y b se definen de la siguiente manera:

In [87]:
a = np.array([1,2,3,4],int)
b = np.array([2,4,6,8] ,int)

¿Qué imprimirá la computadora al ejecutar las siguientes instrucciones? (Trata de averiguar la respuesta antes de intentarlo en la computadora).

a) `print(b/a+1)` 

b) `print(b/(a+1))` 

c) `print(1/a)` 

In [88]:
print(b/a+1)

[3. 3. 3. 3.]


In [89]:
print(b/(a+1))

[1.         1.33333333 1.5        1.6       ]


In [90]:
print(1/a)

[1.         0.5        0.33333333 0.25      ]


## Arreglos numpy (Marices).

Las matrices se tratan como vectores de vectores, o listas de listas:

In [43]:
M = np.array( [ [1, 2], [3, 4] ] )
M

array([[1, 2],
       [3, 4]])

In [45]:
a = np.array([[1,2,3] ,[4,5,6]] ,float)
print(a[1][1])

5.0


In [48]:
b = np.array([[1,2],[3,4], [5,6]], float)
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

También se puede crear una matriz de ceros:

In [49]:
Z=np.zeros([3,4] ,float)
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [55]:
Z.shape

(3, 4)

y de unos:

In [50]:
U = np.ones([3,4] ,float)
print(U)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


La dimensión de la matriz se puede ver con

In [51]:
M

array([[1, 2],
       [3, 4]])

In [52]:
M.shape

(2, 2)

y se puede manipular con

In [53]:
M.shape = 4,1
print(M)

[[1]
 [2]
 [3]
 [4]]


o con

In [56]:
M.reshape( 2, 2 )

array([[1, 2],
       [3, 4]])

también podemos saber el tamaño con `size`

In [57]:
a = np.array([[1,2,3], [4,5,6]] ,int)

print(a.size)
print(a.shape)

6
(2, 3)


Tambien podemos crear una matriz desde una función:

In [58]:
def CreaMatriz(i, j):
    return i+j

M = np.fromfunction(CreaMatriz, (3, 3))

M

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

Dado que las matrices son vectores de vectores, al hacer


In [59]:
print(M[0])

[0. 1. 2.]


nos regresa la primera componente de M, que es justamente un vector (el primer renglón de M). Si queremos cierta entrada de la matriz, entonces más bien necesitamos especificar dos coordenadas:


In [60]:
M[0][1]

np.float64(1.0)

In [61]:
M[0, 1]

np.float64(1.0)

In [62]:
M.item(1)

1.0

In [63]:
a = np.zeros([2,2] ,int)

a[0,1] = 1
a[1,0] = -1

print(a)

[[ 0  1]
 [-1  0]]


Para extraer ciertas renglones o columnas de `M`, utilizamos una extensión de la notación para vectores:

In [67]:
M = np.fromfunction(CreaMatriz, (10, 10))

In [68]:
M

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18.]])

In [69]:
M[2:7]

array([[ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.]])

In [70]:
M[2:7,]

array([[ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.]])

In [71]:
M[2:7,:]

array([[ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.]])

In [72]:
M[2:7,0:5]

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 3.,  4.,  5.,  6.,  7.],
       [ 4.,  5.,  6.,  7.,  8.],
       [ 5.,  6.,  7.,  8.,  9.],
       [ 6.,  7.,  8.,  9., 10.]])

In [73]:
M[2:7,3:5]

array([[ 5.,  6.],
       [ 6.,  7.],
       [ 7.,  8.],
       [ 8.,  9.],
       [ 9., 10.]])

In [74]:
M[2:7, 3:]

array([[ 5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 6.,  7.,  8.,  9., 10., 11., 12.],
       [ 7.,  8.,  9., 10., 11., 12., 13.],
       [ 8.,  9., 10., 11., 12., 13., 14.],
       [ 9., 10., 11., 12., 13., 14., 15.]])

In [75]:
M[2:7, :5]

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 3.,  4.,  5.,  6.,  7.],
       [ 4.,  5.,  6.,  7.,  8.],
       [ 5.,  6.,  7.,  8.,  9.],
       [ 6.,  7.,  8.,  9., 10.]])

In [76]:
M[:7,3:5]

array([[ 3.,  4.],
       [ 4.,  5.],
       [ 5.,  6.],
       [ 6.,  7.],
       [ 7.,  8.],
       [ 8.,  9.],
       [ 9., 10.]])

In [77]:
M[2:,3:5]

array([[ 5.,  6.],
       [ 6.,  7.],
       [ 7.,  8.],
       [ 8.,  9.],
       [ 9., 10.],
       [10., 11.],
       [11., 12.],
       [12., 13.]])

In [78]:
M[:,:]

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18.]])

In [88]:
I = np.identity(10)      #matriz identidad de 10x10
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [89]:
np.trace(I)

np.float64(10.0)

In [83]:
I[3:9, 3:5]  ## ?

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [84]:
I[3:5]

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

Otros métodos útiles son **`diagonal`**, que regresa una diagonal de un arreglo:

In [90]:
np.diagonal(M)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [91]:
np.diagonal(M, 1)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17.])

y **`diag`**, que construye una matriz con el vector dado como diagonal:

In [ ]:
np.diag([1,2,3])

In [ ]:
np.diag([1,2,3], 2)

### **Ejercicio:** 

Realiza el siguiente producto matricial:

$
\begin{pmatrix}
1 & 3\\
2 & 4\\
\end{pmatrix}
\begin{pmatrix}
4 & -2\\
-3 & 1\\
\end{pmatrix}
+2
\begin{pmatrix}
1 & 2\\
2 & 1\\
\end{pmatrix}
=
$ 
<!--$
\begin{pmatrix}
-3 & 5\\
0 & 2\\
\end{pmatrix}
$-->
 

In [94]:
D1 = np.array([[1,3],[2,4]])
D1

array([[1, 3],
       [2, 4]])

In [97]:
D2 = np.array([[4,-2],[-3,1]])
D2

array([[ 4, -2],
       [-3,  1]])

In [98]:
D3 = np.array([[1,2],[2,1]])
D3


array([[1, 2],
       [2, 1]])

In [101]:
(D1*D2)+(2*D3)

array([[ 6, -2],
       [-2,  6]])

In [102]:
np.dot(D1,D2)

array([[-5,  1],
       [-4,  0]])

In [103]:
np.dot(D2,D1)

array([[ 0,  4],
       [-1, -5]])